name: returns_prime_etl - Upload Code to GCS

on:
  push:
    branches:
      - main  # Modify this to match your branch

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip code
        run: zip -r returns_prime_etl.zip .

      - name: Upload to GCS
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          source: returns_prime_etl.zip
          destination: gs://{{ secrets.CLOUD_FUNCTION_BUCKET }}/returns_prime_etl.zip