name: returns_prime_etl - Upload Code to GCS

on:
  push:
    branches:
      - main  # Modify this to match your branch

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip code
        run: zip -r returns_prime_etl.zip .

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
            version: 'latest'
            service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Upload to GCS bucket
        run: gsutil cp returns_prime_etl.zip gs://returns_prime_cf_bucket/