name: Generate whl and deploy to s3
on: [ push ]
jobs:
  libgen-s3upload:
    name: libgen-s3upload
    runs-on: macos-latest
    outputs:
      job-status: ${{ job.status }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'
      - name: Generating python whl file
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          pip install wheel
          chmod +x ./deployment.sh
          ./deployment.sh all